name: swg_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: 
  url_launcher:  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.png
    - assets/images/3.png
    - assets/images/book.png
    - assets/images/grad.png
    - assets/images/profile.png
    - assets/images/group.png
    - assets/images/internship.png
    - assets/images/event_poster.jpg
