name: swg_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  url_launcher:
  carousel_slider: ^4.0.0
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.6.1
  firebase_storage: ^12.1.0
  firebase_core: 
  cloud_firestore:
  rxdart: ^0.27.7  
  shared_preferences: ^2.2.3
  http: ^1.2.1
  path_provider: ^2.1.3
  firebase_messaging: ^15.0.4
  awesome_notifications: ^0.9.3+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/swg.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/fundae-docs/
    - assets/images/swg-events/
    - assets/images/insti-id-benifits/
    - assets/images/
    - assets/icons/
    - assets/images/dept logo/
    - assets/images/blue/
