// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zmjjlF54ZON1pDgaoWLgFUaBwSuOJvQ',
    appId: '1:577661051293:web:9fb5cf665bed618b984f74',
    messagingSenderId: '577661051293',
    projectId: 'swg-app-ddf90',
    authDomain: 'swg-app-ddf90.firebaseapp.com',
    storageBucket: 'swg-app-ddf90.appspot.com',
    measurementId: 'G-DZ08074G4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzi3YdD_QEKqfGcbvEPXNWo9CjFrsrv0',
    appId: '1:577661051293:android:9994b1bcd85d83e5984f74',
    messagingSenderId: '577661051293',
    projectId: 'swg-app-ddf90',
    storageBucket: 'swg-app-ddf90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjphyL6_f6Wlv3qNNKXQ9w_-NDvv4Qc7U',
    appId: '1:577661051293:ios:3b333b8147d617ae984f74',
    messagingSenderId: '577661051293',
    projectId: 'swg-app-ddf90',
    storageBucket: 'swg-app-ddf90.appspot.com',
    iosBundleId: 'com.example.swgFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjphyL6_f6Wlv3qNNKXQ9w_-NDvv4Qc7U',
    appId: '1:577661051293:ios:3b333b8147d617ae984f74',
    messagingSenderId: '577661051293',
    projectId: 'swg-app-ddf90',
    storageBucket: 'swg-app-ddf90.appspot.com',
    iosBundleId: 'com.example.swgFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zmjjlF54ZON1pDgaoWLgFUaBwSuOJvQ',
    appId: '1:577661051293:web:fde83d3f8a377e57984f74',
    messagingSenderId: '577661051293',
    projectId: 'swg-app-ddf90',
    authDomain: 'swg-app-ddf90.firebaseapp.com',
    storageBucket: 'swg-app-ddf90.appspot.com',
    measurementId: 'G-VNEMFQCC75',
  );

}